export const ELEMENTS = {
    loginIcon: '.belcorp-belcorp-challenge-0-x-loginText',
    loginIconMobile: '.belcorp-belcorp-challenge-0-x-loginButton',
    clicIniciarSesion : '#__next > main > div > form > button',
    email : '#email',
    password : '#password',
    emailInvalid : '.inputErrorText_inputErrorText__ejTgA',
    passwordInvalid : '#__next > main > div > form > div:nth-child(7) > span > span',
    olvidPassword : '#__next > main > div > form > a',
    titleRestabPassword : '#__next > main > div > h6',
    txtemailinvalid: '#__next > main > div > form > div > span > span',
    txtAunNoCuenta: '#__next > main > div > div > h6',
    clicCrearCuenta: '#__next > main > div > div > button',
    txtCampRequeNom: '#__next > main > div > form > div:nth-child(1) > span > span',
    txtCampRequeApe: '#__next > main > div > form > div:nth-child(2) > span > span',
    txtCamprequeEmail: '#__next > main > div > form > div:nth-child(3) > span > span',
    txtCamprequeConfPass: '#__next > main > div > form > div:nth-child(6) > span > span',
    txtConfPass: '#confirmpassword',
    txtnomb: '#firstname',
    txtapell:'#lastname',
    clicOptiona:'#__next > main > div > form > div:nth-child(6) > div:nth-child(1) > div > label > svg',
    clicTerm:'#__next > main > div > form > div:nth-child(6) > div:nth-child(2) > div > label > svg',
    txtBienv: '.belcorp-belcorp-challenge-0-x-loginText',
    txtCreatAccount: "#__next > main > div > h6",
    nameLoggedMyAccount: '.vtex-my-account-1-x-userName'

}