export const ELEMENTS = {
    itemCategoryMainBanner: '.pr0 > .vtex-store-components-3-x-imageElement',
    itemCategoryMainBannerMobile: '.vtex-store-components-3-x-imageElement',
    itemCategoryBtnMore: '.vtex-search-result-3-x-buttonShowMore > .vtex-button > .vtex-button__label',
    itemCategoryBtnMoreText: 'div.pr0.items-stretch.flex-grow-1.flex > div > div:nth-child(4) > div > div > div > div > div > a > div',
    itemCategoryBtnMoreTextPE: '.vtex-search-result-3-x-buttonShowMore > .vtex-button > .vtex-button__label',
    itemCategoryBreadCrumb: '[data-testid=breadcrumb]',
    itemCategoryBreadCrumbHome: '.vtex-breadcrumb-1-x-homeLink',
    itemCategoryBreadCrumbName: '.vtex-breadcrumb-1-x-arrow > .vtex-breadcrumb-1-x-link',
    itemCategoryOrderTitle: '.vtex-search-result-3-x-filterPopupTitle',
    itemCategoryOrderTitleMobile: '.vtex-search-result-3-x-orderByButton > .vtex-search-result-3-x-filterPopupTitle',
    itemCategoryOrderArrow: '#nav-caret--down',
    itemCategoryOrderBtn: '.vtex-search-result-3-x-filterPopupArrowIcon',
    itemCategoryOrderBtnMobile: '.vtex-search-result-3-x-orderByButton',
    itemCategoryOrderFirstOption: `//button[contains(text(),'Relevancia')]`,
    itemCategoryOrderFirstOptionMTO: '.bg-light-gray',
    itemCategoryOrderOptions: 'button.hover-bg-muted-5.bg-base.vtex-search-result-3-x-orderByOptionItem.c-on-base.f5.ml-auto.db.no-underline.pointer.tl.bn.pv4.ph5.w-100.right-0-ns',
    itemCategoryProductCard: '#gallery-layout-container > :nth-child(1)',
    itemCategoryProductImage: 'img.vtex-product-summary-2-x-imageNormal.vtex-product-summary-2-x-image.vtex-product-summary-2-x-image--product-search-image',
    itemCategoryProductName: 'span.vtex-product-summary-2-x-productBrand.vtex-product-summary-2-x-productBrand--product-search-name.vtex-product-summary-2-x-brandName.vtex-product-summary-2-x-brandName--product-search-name.t-body',
    itemCategoryProductPrice: 'span.vtex-product-price-1-x-sellingPriceValue.vtex-product-price-1-x-sellingPriceValue--product-search-price',
    itemCategoryProductBtn: 'div.vtex-button__label.flex.items-center.justify-center.h-100.ph6.w-100.border-box',
}
